import { createMockDb } from '../../helpers/mockDb';
import { describe, it, expect, jest } from '@jest/globals';
import { smcCreateRound, smcListRounds, smcUpdateRoundStatus } from '@/db/queries/smc-rounds';
import { RoundStatus, type RoundListItem } from '@/lib/types';

let mockUuidCounter = 0;
jest.mock('expo-crypto', () => ({
  randomUUID: jest.fn(() => `uuid-${mockUuidCounter++}`),
}));

describe('smcCreateRound', () => {
  it('creates the round, its squad, and the creator entry in one transaction', async () => {
    mockUuidCounter = 0;
    const db = createMockDb();

    const result = await smcCreateRound(db, {
      created_by: 'user1',
      creator_name: 'Alice',
      ground_name: 'Club Alpha',
      date: '2026-03-28',
      total_targets: 100,
      club_id: null,
    });

    // Identity generated by the module and returned to the caller.
    expect(result).toEqual({ roundId: 'uuid-0', squadId: 'uuid-1' });

    // All three writes happen atomically inside a single transaction.
    expect(db.writeTransaction).toHaveBeenCalledTimes(1);
    const tx = await db.writeTransaction.mock.results[0].value;

    expect(tx.execute).toHaveBeenCalledWith(
      expect.stringContaining('INSERT INTO rounds'),
      expect.arrayContaining(['uuid-0', 'user1', 'Club Alpha', '2026-03-28', 100, RoundStatus.SETUP]),
    );
    expect(tx.execute).toHaveBeenCalledWith(
      expect.stringContaining('INSERT INTO squads'),
      ['uuid-1', 'uuid-0'],
    );
    expect(tx.execute).toHaveBeenCalledWith(
      expect.stringContaining('INSERT INTO shooter_entries'),
      ['uuid-2', 'uuid-1', 'uuid-0', 'user1', 'Alice', 1],
    );
  });
});

describe('smcListRounds', () => {
  it('requests conflict-aware rounds for owner or participant', async () => {
    const db = createMockDb();
    const rows: RoundListItem[] = [
      {
        id: 'round1',
        created_by: 'user1',
        ground_name: 'Club Alpha',
        date: '2026-03-28',
        total_targets: 100,
        status: RoundStatus.COMPLETED,
        notes: null,
        club_id: null,
        created_at: '2026-03-28T10:00:00Z',
        updated_at: '2026-03-28T10:00:00Z',
        has_unresolved_conflicts: 1,
      },
    ];
    (db.getAll as any).mockResolvedValue(rows);

    const result = await smcListRounds(db, 'user1');

    expect(result).toEqual(rows);

    const [sql, params] = (db.getAll as any).mock.calls[0];
    expect(sql).toContain('has_unresolved_conflicts');
    expect(sql).toContain('HAVING COUNT(*) > 1');
    expect(params).toEqual(['user1', 'user1']);
  });
});

describe('smcUpdateRoundStatus', () => {
  it('updates round status with timestamp', async () => {
    const db = createMockDb();

    await smcUpdateRoundStatus(db, 'round1', RoundStatus.IN_PROGRESS);

    expect(db.execute).toHaveBeenCalledWith(
      'UPDATE rounds SET status = ?, updated_at = ? WHERE id = ?',
      [RoundStatus.IN_PROGRESS, expect.any(String), 'round1'],
    );
  });
});
